apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron
spec:
  concurrencyPolicy: "Replace"
  jobTemplate:
    spec:
      template:
        spec:
          shareProcessNamespace: true
          containers:
          - name: cron
            image: some-image
            imagePullPolicy: Always
            ports:
              - containerPort: 3001
            command: ["/bin/sh"]
            args: ["-c", "node commands/cronjobs/$(CRON_FILE)"]

          restartPolicy: OnFailure
