apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cron
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron
            env:
            - name: CRON_FILE
              value: "test2.js"
