apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  template:
    spec:
      nodeSelector:
        environment: staging

      volumes:
      - name: some-volume
        secret:
          secretName: some-secret
