commonLabels:
  environment: staging

bases:
- ../../base
- ../../cronjobs

patches:
- path: deployment.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
- path: cronjob.yaml
  target:
    group: batch
    version: v1beta1
    kind: CronJob
